version: '3'
networks:
  traefik:
    external:
      name: plataforma_network
services:
    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL = admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD = admin
        - SCRIPT_NAME=/pgadmin
      volumes:
        - pgadmin:/root/.pgadmin
      ports:
        - "5050:80"
      networks:
        - traefik
      restart: unless-stopped
      labels:
        - "traefik.backend=pgadmin"
        - "traefik.docker.network=plataforma_network"
        - "traefik.frontend.priority=600" 
        - "traefik.frontend.rule=Method:GET" 
        - "traefik.frontend.rule=PathPrefix:/pgadmin"  
        - "traefik.port=80"
volumes:
    pgadmin: